-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID , ANIMAL_OUTS.NAME
FROM ANIMAL_INS right join ANIMAL_OUTS USING (ANIMAL_ID)
WHERE 1=1
AND ANIMAL_INS.ANIMAL_ID IS NULL
AND ANIMAL_OUTS.ANIMAL_ID IS NOT NULL


