WITH CJ AS (
SELECT  RH.HISTORY_ID
        ,C.CAR_TYPE
        ,C.DAILY_FEE
        ,DATEDIFF(RH.END_DATE,RH.START_DATE)+1 AS DAYS
  FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
  JOIN  CAR_RENTAL_COMPANY_CAR AS C
    ON  RH.CAR_ID = C.CAR_ID
 WHERE  C.CAR_TYPE = '트럭'
)
, CAR_RENTAL AS (
SELECT  CJ.*
        ,CASE 
        WHEN DAYS >= 90 THEN 15
        WHEN DAYS >= 30 THEN 8
        WHEN DAYS >= 7 THEN 5
        ELSE 0 END RATE
  FROM  CJ
  JOIN  CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
    ON  CJ.CAR_TYPE = DP.CAR_TYPE
 GROUP
    BY  CJ.HISTORY_ID
)

SELECT  HISTORY_ID
        ,ROUND(DAILY_FEE * DAYS * (1-RATE*0.01),0) AS FEE
  FROM  CAR_RENTAL
 ORDER
    BY  FEE DESC, HISTORY_ID DESC