-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
WHERE A.ITEM_ID IN (
SELECT B.ITEM_ID
FROM ITEM_TREE B
WHERE EXISTS (
SELECT 1
FROM ITEM_INFO
WHERE ITEM_ID = B.PARENT_ITEM_ID
AND RARITY = 'RARE'
)
)
Order BY ITEM_ID DESC
;