WITH TOP_BOARD AS(
SELECT  BOARD_ID
  FROM  USED_GOODS_BOARD
 ORDER
    BY  VIEWS DESC
 LIMIT  1)

SELECT  CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) as FILE_PATH
  FROM  USED_GOODS_FILE AS UGF
 WHERE  UGF.BOARD_ID =(
         SELECT  BOARD_ID
           FROM  TOP_BOARD)
 ORDER
    BY  FILE_ID DESC
;